astrocamp/15th-RestTime

app/javascript/controllers/application.js

fix import js problem

---

app/controllers/shops_controller.rb
app/helpers/products_helper.rb
app/models/product.rb
app/models/shop.rb
app/views/shops/index.html.erb
config/locales/tw.yml
db/migrate/20231222135548_remove_store_id_and_index_from_products.rb
db/migrate/20231222140539_add_shop_to_product.rb
db/schema.rb

新增商店頁排序按鈕 & i18n (Feat#issue 09)

---

config/locales/tw.yml
package.json

修正tw.yml及request套件問題

---

app/assets/stylesheets/application.tailwind.css
app/controllers/vendor_controller.rb
app/policies/product_policy.rb
app/views/layouts/vendor.html.erb
app/views/products/_form.html.erb
app/views/products/_item.html.erb
app/views/products/my.html.erb
app/views/shops/_shop.html.erb
app/views/vendor/_form_select_shop_status.html.erb
app/views/vendor/_like_shops.html.erb
app/views/vendor/_shop.html.erb
app/views/vendor/index.html.erb
app/views/vendor/show.html.erb
config/locales/en.yml
config/locales/tw.yml
config/routes.rb

後台-商品維護功能(Vendor) Feat issue 60 & 66

---

app/views/layouts/vendor.html.erb
app/views/products/index.html.erb
app/views/products/my.html.erb
app/views/shops/index.html.erb
app/views/vendor/_sidebar.html.erb
app/views/vendor/index.html.erb
config/locales/tw.yml

- 此為基於feat-issue-74新開的分支，所以有多了很多commit紀錄，僅有b9a7ff93為此次PR的更動
- 除了自己新增的sidebar頁面外，其他都是調整css的排版樣式or縮排or調整位置，讓畫面可以正常顯示，沒有調整程式碼邏輯
- 主要更動後台layout，layout>vendor.html.erb
- 增加側面side bar，位置 vendor>_sidebar.html.erb
- Demo 影片：
https://youtu.be/-duyTk4LpgA
- 改了一個我的商品的i18n連結

後台畫面css調整 Feat issue 75

---

app/controllers/vendor_controller.rb
app/helpers/application_helper.rb
app/policies/application_policy.rb
app/views/layouts/vendor.html.erb
app/views/products/_form.html.erb
app/views/products/my.html.erb
app/views/shops/_form.html.erb
app/views/vendor/_form_select_shop_status.html.erb
app/views/vendor/_sidebar.html.erb
app/views/vendor/index.html.erb
config/locales/tw.yml

續接`feat-issue-75`加入**後台編輯店家**
- 整理表單CSS一致性
- 側邊欄微調
- 加入i18n

後台-編輯店家資訊功能和整理#feat-issue-46-1

---

app/views/layouts/application.html.erb
app/views/layouts/vendor.html.erb
app/views/pages/index.html.erb

- 在layout增加 mt-20，增加與navbar的間距
- 效果：
vendor後台：

調整navbar間距 Feat issue 90

---

app/controllers/vendor_controller.rb
app/policies/application_policy.rb
app/policies/product_policy.rb
app/policies/shop_policy.rb

- 原本寫在policy內，調整改到vendor_controller
- 調整Policy，改為 ```user.vendor? || user.admin?``` 其中之一符合即可進入頁面
- user.roler=vendor的current_user預設進入vendor頁面後，預設產生商店給他（排除admin）
demo影片：
https://github.com/astrocamp/15th-RestTime/assets/147526390/3531e967-978b-4a8b-a5e5-2b00a94af9a5

修改新增預設商店的方法位置 Feat issue 92

---

app/views/layouts/application.html.erb
app/views/layouts/vendor.html.erb
app/views/shared/_flash.html.erb

- 修改layou（application & vendor）
- 修改flash頁面，x改為黑色
修改後如下：

修改layout讓flash出現，Feat issue 95

---

app/controllers/users/omniauth_callbacks_controller.rb
app/views/orders/show.html.erb

- 修正Google登入後返回系統出現錯誤問題
- 修正訂單內容路徑錯誤問題

修正第三方登入及訂單路徑

---

app/controllers/comments_controller.rb
config/locales/tw.yml

修改comment_controller功能（feat-issue-109）

---

app/controllers/products_controller.rb
app/models/product.rb
app/views/pages/index.html.erb
app/views/products/index.html.erb
config/locales/tw.yml

- 改寫i18n
- 分頁因為都為8頁，所以改寫到model `paginates_per 8`
- 調整搜尋邏輯，刪除不必要的程式碼
- 微調Pundit格式

修改product_controller & product.md (Feat issue 107)

---

package.json

將只需在開發環境使用項目移到devDependencies內
- tailwindcss
- esbuild
- postcss
- autoprefixer

修改package.json

---

app/controllers/application_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/vendor_controller.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
config/locales/tw.yml
config/routes.rb

- codereview後修改vendor_controller
- 把新增預設商店搬到User model
- 新增註冊選項，可以選角色為vendor，成功後跳轉至編輯商店頁面
- 新增user>registration_controller，將轉址寫在裡面，另外亦更改routes，以符合更動
- vendor註冊示例影片：
https://github.com/astrocamp/15th-RestTime/assets/147526390/613e055b-5921-478d-aa9f-a0fe3ad96403

修改新增預設商店至model & 修改vendor_controller (Feat issue 112)

---

app/avo/resources/comment.rb
app/avo/resources/like_shop.rb
app/avo/resources/product.rb
app/avo/resources/shop.rb
app/avo/resources/user.rb
app/controllers/orders_controller.rb
app/controllers/shops_controller.rb
app/controllers/vendor/orders_controller.rb
app/helpers/application_helper.rb
app/helpers/products_helper.rb
app/models/comment.rb
app/models/order.rb
app/models/shop.rb
app/policies/product_policy.rb
app/policies/shop_policy.rb
app/views/vendor/orders/confirm_redeem.html.erb
app/views/vendor/orders/my.html.erb
config/locales/tw.yml

- 修改前台order遺漏未刪除controller
- 調整以及縮排程式碼
- 修正後台vendor錯誤

修改vendor_order_controller & order_controller<部分>(Feat issue 110)

---

app/avo/resources/user.rb
app/controllers/shops_controller.rb
app/models/shop.rb
app/views/vendor/orders/my.html.erb

- 調整預設頁數移至shop model
- 修正方法命名
- 移除重複性程式碼
- 縮排整理

修改調整shop_controller(Feat issue 114)

---

app/controllers/orders_controller.rb
app/controllers/shops_controller.rb
app/controllers/vendor/orders_controller.rb
app/models/order.rb
app/views/bookings/_form.html.erb
app/views/bookings/checkout.html.erb
app/views/orders/_order.html.erb
app/views/orders/_order_table.html.erb
app/views/orders/create.html.erb
app/views/orders/edit.html.erb
app/views/orders/my_bookings.html.erb
app/views/orders/show.html.erb
app/views/products/my.html.erb
app/views/shared/_navbar.html.erb
app/views/shops/_booking.html.erb
app/views/shops/index.html.erb
app/views/vendor/_sidebar.html.erb
app/views/vendor/orders/_order_table.html.erb
app/views/vendor/orders/confirm_redeem.html.erb
app/views/vendor/orders/my.html.erb
app/views/vendor/orders/show.html.erb
app/views/vendor/show.html.erb
config/locales/en.yml
config/locales/tw.yml
config/routes.rb

- 增加修改預約日期，取消訂單
- 判斷使用者若更改時間是一樣的，無法更改時間(維持原頁面)
- 取消訂單送出後，帶入取消日期
- 根據aasm狀態去顯示對應的連結
- 移除aasm confirm 狀態，預設pending
- 修改my_booking頁面

[預約]變更/取消/修改/前台我的預約畫面Feat issue 28

---

app/controllers/orders_controller.rb
app/controllers/vendor/orders_controller.rb
app/mailers/order_mailer.rb
app/models/order.rb
app/views/order_mailer/cancel_order_email_to_general.html.erb
app/views/order_mailer/cancel_order_email_to_vendor.html.erb
app/views/order_mailer/change_order_email_to_general.html.erb
app/views/order_mailer/change_order_email_to_vendor.html.erb
app/views/order_mailer/new_order_email_to_general.html.erb
app/views/order_mailer/new_order_email_to_vendor.html.erb
app/views/order_mailer/redeem_order_email_to_general.html.erb
app/views/order_mailer/redeem_order_email_to_vendor.html.erb
config/locales/tw.yml

- 通知雙方General和Vendor
- 目前訂單成立預設(已付款)才寄出
- General收到信件內容：
- Vendor收到信件內容可以去共用信箱查看

[預約]預約通知信件Feat issue 25

---

app/controllers/users/omniauth_callbacks_controller.rb
app/models/user.rb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
config/locales/tw.yml
db/schema.rb

修正編輯頁面與GOOGEL登入修改密碼頁

---

app/assets/stylesheets/application.tailwind.css
app/views/vendor/orders/_order_table.html.erb

- 核銷頁面排版
- 重複核銷自動跳轉首頁
- 先拔除sidebar畫面置中

核銷畫面切版Feat issue 127

---

app/controllers/shops_controller.rb
app/models/comment.rb
app/views/orders/_order.html.erb
app/views/shops/show.html.erb
config/locales/tw.yml

- 修改店家評論至我的訂單，擁有訂單的人才能評論
頁面示意：
能從我的預約右下角看到評論按鈕
只有擁有訂單，才會渲染comment.form
- 目前尚未完成限制一個訂單僅能評價一次，後續會再開issue完成

使用者擁有訂單才能夠評論 - Issue 161

---

app/views/shared/_navbar.html.erb
app/views/vendor/_navbar.html.erb
app/views/vendor/_sidebar.html.erb
app/views/vendor/index.html.erb

一般使用者：
一般使用者手機：
後台商家：
後台商家手機：
- 調整i18n
- 調整前後台navbar,商家後台首頁，使手機畫面能正常顯示

更新RWD fetch(nav&vendor_index):新增RWD issue-169

---

app/views/pages/index.html.erb

調整首頁下方RWD Issue 172

---

app/controllers/application_controller.rb
config/routes.rb

修正登入打錯密碼會直接報錯

---

app/views/pages/index.html.erb
app/views/shared/_navbar.html.erb
config/locales/tw.yml

- 增加placeholder
- 增加i18n
- 新進店家：改導店家（更新時間排序）
- 冬季按摩：導搜尋「按摩」的結果頁
- 美甲口碑：導搜尋「美甲」的結果頁

searchbar placeholder & 首頁連結 Issue 183

---

app/controllers/shops_controller.rb
app/controllers/vendor_controller.rb
app/models/shop.rb
app/models/user.rb
app/views/shops/edit.html.erb
app/views/vendor/_form.html.erb

- 增加必填欄位提示
- 刪除商店簡介必填的驗證
- 修理：商店更新時，必填爛位填寫錯誤會導至錯誤畫面

提示必填欄位 Issue179

---

app/controllers/orders_controller.rb
app/models/order.rb
app/policies/order_policy.rb

- 修正使用者查看預約訂單會顯示全站預約單問題
- 修正後只顯示使用者的訂單
- 增加order訂單顯示修改及更新的權限限制

order 只顯示my order

---

app/assets/stylesheets/application.tailwind.css
app/controllers/orders_controller.rb
app/controllers/products_controller.rb
app/controllers/shops_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/product_info_controller.js
app/javascript/controllers/scroll_controller.js
app/views/layouts/application.html.erb
app/views/orders/show.html.erb
app/views/products/_booking.html.erb
app/views/products/_booking_sm.html.erb
app/views/products/show.html.erb
app/views/shared/_business_hours.html.erb
app/views/shared/_shop_info.html.erb
app/views/shops/show.html.erb
config/locales/tw.yml

RWD商品show Feat issue 168

---

app/views/products/_product.html.erb
app/views/shared/_shop_info.html.erb

- 目前畫面
https://youtube.com/shorts/sWlyJWYh0ms?feature=share

RWD商店show Feat issue 192

---

app/views/comments/_comment.html.erb
app/views/comments/_form.html.erb
app/views/orders/_form.html.erb
app/views/orders/create.html.erb
app/views/orders/new.html.erb
app/views/products/_form.html.erb
app/views/products/_item.html.erb
app/views/products/edit.html.erb
app/views/service_times/_input_time.html.erb
app/views/service_times/_service_times.html.erb
app/views/service_times/edit.html.erb
app/views/shared/_navbar.html.erb
app/views/vendor/_navbar.html.erb

- 修正訂單無法跳轉至綠界付款頁面問題
https://github.com/astrocamp/15th-RestTime/assets/8993798/1df8526c-2452-4b91-bf62-43a772638134
- 商品頁價格顯示整數價格

小鈴鐺通知於safari上無作用及部分頁面版面微調

---

app/assets/stylesheets/application.tailwind.css
app/views/products/index.html.erb
app/views/shops/index.html.erb

paginate 樣式 # Issue 187

---

.gitignore
app/controllers/products_controller.rb
app/controllers/shops_controller.rb
app/views/comments/_comment.html.erb
app/views/layouts/application.html.erb
app/views/pages/index.html.erb
app/views/products/_product.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb
app/views/service_times/edit.html.erb
app/views/shared/_business_hours.html.erb
app/views/shared/_navbar.html.erb
app/views/shops/_shop.html.erb
app/views/shops/index.html.erb
app/views/shops/search.html.erb
app/views/shops/show.html.erb
app/views/vendor/_form.html.erb
app/views/vendor/_navbar.html.erb
app/views/vendor/_sidebar.html.erb
app/views/vendor/orders/my.html.erb
config/locales/tw.yml

Navbar- 我的後台配色
首頁 - 首頁 banner 圖壓縮
RWD - 前後台加邊界 + 調整排版
搜尋頁 - 調整樣式
- 調整nav字體大小

Demo反饋修改 Issue 214 （nav,homepage,search,前後台margin）

---

app/helpers/application_helper.rb

店家地址 Issue 225

---

app/assets/stylesheets/application.tailwind.css
app/controllers/shops_controller.rb
app/controllers/vendor/orders_controller.rb
app/models/order.rb
app/views/order_mailer/new_order_email_to_general.html.erb
app/views/order_mailer/new_order_email_to_vendor.html.erb
app/views/orders/_order.html.erb
app/views/orders/index.html.erb
app/views/shops/_shop.html.erb
app/views/shops/index.html.erb
app/views/shops/show.html.erb
app/views/vendor/orders/_order_table.html.erb
app/views/vendor/orders/_order_table_sm.html.erb
app/views/vendor/orders/my.html.erb
app/views/vendor/orders/show.html.erb
config/locales/tw.yml

前台畫面：
https://youtube.com/shorts/RfKAjG2Cvhw?feature=share
後台畫面：
https://youtube.com/shorts/nQzXg6kzJCk?feature=share
- 日曆手機版因為時間不足，先拉掉

訂單前後台頁面修正RWD Feat issue 217

---

Gemfile.lock
app/helpers/orders_helper.rb
app/views/vendor/orders/_calendar.html.erb

fetch(calendar):新增完成訂單color & 更改連結 (issue-234)

---

app/views/shops/search.html.erb

搜尋頁面欄位置中 Issue 242

---

app/views/vendor/_navbar.html.erb
app/views/vendor/_sidebar.html.erb

解決mobile顯示異常＆調整我的後台badge位置
mobile 
PC

後台navbar , 前台首頁放到漢堡裡 Issue 233

---

app/models/shop.rb

修正營業時間判斷問題

---

app/controllers/avo/shops_controller.rb
app/views/products/show.html.erb
app/views/shops/show.html.erb

預設圖片Feat issue 240

---

app/controllers/shops_controller.rb

- 搜尋摩羯可以搜尋到
- 搜尋按摩，依照更新時間排序，最新新建的店放在第一個

fix(search):搜尋修正 & 依照更新時間排序

---

app/helpers/orders_helper.rb
app/views/simple_calendar/_month_calendar.html.erb
app/views/vendor/orders/_calendar.html.erb
app/views/vendor/orders/my.html.erb

- 原本已付款因為demo反應背景黃色太淺，因此改為深咖色
- 原本爆版已修正
影片：
https://github.com/astrocamp/15th-RestTime/assets/147526390/04f1bf65-71ec-41a6-a3b0-80a499e9ffe4

fix(calendar):標籤顏色修改&爆版更正

---

app/models/order.rb
app/views/order_mailer/new_order_email_to_general.html.erb
app/views/order_mailer/new_order_email_to_vendor.html.erb
app/views/orders/edit.html.erb
app/views/orders/new.html.erb
app/views/orders/show.html.erb
app/views/products/_booking.html.erb
app/views/products/_booking_sm.html.erb
app/views/shops/_booking.html.erb
config/locales/tw.yml

- 預約提示字添加"選擇時段"
- 修復product 沒照片判斷miss
- mailer 信件內容價格移除小數點、付款方式添加i18n

預約提示字，mailer修正 Feat issue 247

---

app/views/products/show.html.erb
app/views/shared/_footer.html.erb
app/views/shops/show.html.erb

修正footer 手機版index錯誤

---

app/views/orders/_form.html.erb
app/views/orders/new.html.erb

手機確認預約固定在表格下方 Issue 256

---

app/views/orders/_order.html.erb
app/views/orders/edit.html.erb
app/views/orders/show.html.erb

- 連結區塊可點擊
- 手機版加入再付款連結
- 修正修改時間出現錯誤訊息
https://github.com/astrocamp/15th-RestTime/assets/114802512/cdc9c645-d983-4001-857a-0b93e59e079d

更改預約時間頁面修正Feat issue 259

---

app/views/vendor/orders/_calendar.html.erb
app/views/vendor/orders/my.html.erb

https://github.com/astrocamp/15th-RestTime/assets/147526390/9949d614-7ec2-4fdd-af27-4955058ec035

fix(myorder):恢復不見的order&calendar標題置中

---

app/views/comments/_form.html.erb

fix(comment):寬度改auto
